name: Go Build and Test

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'  # Change this to your desired Go version

      - name: Test
        run: |
          echo "Testing started"
          go test -v

  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'  # Change this to your desired Go version

      - name: Compile
        run: |
          go build power-interruption-logging-system/main.go
          echo "Successfully built go .exe for power interruption checker"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deployment
        run: echo "Define your deployment script!"
